.\" $Id: iptables-management.8 5891 27.04.2015 12:53:09Z aron $
.TH iptables-management 8 27.04.2015 iptabels "iptables-management" 
.\" Process with
.\" groff -man -Tascii iptables-management.8 
.\"
.SH NAME
iptables-management \- iptables management utility

.SH SYNOPSIS
.B service iptables-management 
.BI [start|stop|restart]

.SH DESCRIPTION
.B iptables-management
Provides is a utililty tool for managing iptables rules and is loaded at boot time. It is equivilant to
.IB iptables-persistent
by providing almost the exact same functionality in addition to, allowing packages to install rules within the provided directories.
The rules are generated every time iptables-management is reloaded and is saved to
.I /etc/iptables/ipv4/rules
and
.I /etc/iptables/ipv6/rules
from where it is then loaded to
.I iptabels
and
.I ip6tables
respectivly.

.SH FILES
.PD 0
.I /etc/iptables/
.br
.IB /etc/iptables/ipv4/
.br
.IB /etc/iptables/ipv6/
.br
.IB /etc/iptables/ipv4/rules
.br
.IR /etc/iptables/ipv4/TABLE/
.br
.IB /etc/iptables/ipv4/TABLE/CHAIN/
.br
.IB /etc/iptables/ipv4/TABLE/CHAIN/defaults.rules
.br
.IB /etc/iptables/ipv4/TABLE/CHAIN/0_accept/
.br
.IB /etc/iptables/ipv4/TABLE/CHAIN/0_drop/
.br
.IB /etc/iptables/ipv4/TABLE/CHAIN/1_accept/
.br
.IB /etc/iptables/ipv4/TABLE/CHAIN/1_drop/
.br
.IB /etc/iptables/ipv6/rules
.br
.IR /etc/iptables/ipv6/TABLE/
.br
.IB /etc/iptables/ipv6/TABLE/CHAIN/
.br
.IB /etc/iptables/ipv6/TABLE/CHAIN/defaults.rules
.br
.IB /etc/iptables/ipv6/TABLE/CHAIN/0_accept/
.br
.IB /etc/iptables/ipv6/TABLE/CHAIN/0_drop/
.br
.IB /etc/iptables/ipv6/TABLE/CHAIN/1_accept/
.br
.IB /etc/iptables/ipv6/TABLE/CHAIN/1_drop/
.br

.SH AUTHORS
.PP
Authored by Aron Podrigal. <aron@mongotel.com>.

.SH BUGS
Report bugs to devops@mongotel.com - MongoTEL development

.SH SEE ALSO
.R iptables-management(5),\ iptables(8),\ ip6tables(8)
.PP
.nf 
